# Generated by Django 5.2.5 on 2025-08-31 10:44

import backend.resume_parser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=backend.resume_parser.models.resume_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('questions', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
